version: "3.9"

services:

  backend:
    build: ./server
    container_name: upload-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped

  frontend:
    build: ./client
    container_name: upload-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped